### ISSUE TITLE
White mushroom fence beams missing texture

### ISSUE THREAD

**Issue by ManaStar** [teamauroramods/EnhancedMushrooms#3]
![image](https://user-images.githubusercontent.com/78570904/169657685-609c64c2-00e9-431d-9fde-4e4898702f43.png)

![image](https://user-images.githubusercontent.com/78570904/169657784-7631c6a8-c470-49cd-8fcd-3943c319f834.png)
I assume that whatever the issue that is happening here would also apply to the brown version.

**Comment by ebo2022** [comment]
I can't seem to reproduce this issue on my end. Do you mind sending a mod list, or a link to the modpack you're playing?

**Comment by ex0planetary** [comment]
Looks to me like a resource pack issue. Back when I still played a lot of MC one of the vanilla-style resource packs I used to use did this. IIRC there was another version without fence model changes. Might've been Peeves or Farcr's Texture Overrides? idk

**Comment by ebo2022** [comment]
I'll close the issue for now, but if someone finds anything that could be on our end make sure to let us know

**Comment by ManaStar** [comment]
> Looks to me like a resource pack issue. Back when I still played a lot of MC one of the vanilla-style resource packs I used to use did this. IIRC there was another version without fence model changes. Might've been Peeves or Farcr's Texture Overrides? idk

You nailed it with Peeves, is not on your end end at all. Sorry for wasting time!
