### ISSUE TITLE
Can't craft mushroom boats

### ISSUE THREAD

**Issue by TheRealBrobie** [teamauroramods/EnhancedMushrooms#4]
As the title implies, I can't craft mushroom boats. The recipes do not show in JEI/EMI. Not sure if this is a bug or a config option but I also could not find a config for EM.

MC ver 1.18.2
Fabric ver 0.14.8
EM ver 4.0.0
Pollen ver 1.4.4

**Comment by ebo2022** [comment]
fixed in the latest release
