### ISSUE TITLE
Add Fabric 1.16 and 1.17 versions to curseforge.com

### ISSUE THREAD

**Issue by pavog** [teamauroramods/EnhancedMushrooms#5]
Hi, can you please add the versions for Fabric 1.16 and 1.17 to [enhanced-mushrooms](https://www.curseforge.com/minecraft/mc-mods/enhanced-mushrooms)?
I know that they exist on [enhanced-mushrooms-fabric](https://www.curseforge.com/minecraft/mc-mods/enhanced-mushrooms-fabric), but I would like to only use one project / project page on curseforge.com, not two.
Can you just copy them over from [enhanced-mushrooms-fabric](https://www.curseforge.com/minecraft/mc-mods/enhanced-mushrooms-fabric) to [enhanced-mushrooms](https://www.curseforge.com/minecraft/mc-mods/enhanced-mushrooms)?

**Comment by ebo2022** [comment]
Not currently planned
