### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by turnipjs** [teamauroramods/EnhancedMushrooms#6]
I am working on updating my modpack to 1.19.2. I really love this mod and would like to be able to include it!

**Comment by ebo2022** [comment]
Soon, pollen needs to update first

**Comment by Sshmoob** [comment]
Don't know if you know this, but pollen has updated to 1.19.2.

**Comment by ebo2022** [comment]
We have updated our trajectory a little bit:
1. we'll be skipping 1.19 and porting straight to 1.20
2. we are going to be using our own library in future releases
3. This will eventually be merged into Novel but will likely see a 1.20 release until we finish work on that mod

**Comment by Sshmoob** [comment]
~If I ported it to 1.19.2 myself and made a pull request, would you still upload that version to curseforge?~
Edit: Nevermind, I just realized it's multiloader, which I don't know how to work with.

**Comment by ebo2022** [comment]
possibly- go ahead if you want to but we aren't endorsing/supporting it until you're finished/we merge the pull
