### ISSUE TITLE
Needs abnormals_core?

### ISSUE THREAD

**Issue by Oddlybird** [teamauroramods/EnhancedMushrooms#7]
So, I downloaded the version for 1.16, and I downloaded Pollen which the main description claims it needs.  ...but, when I try to run minecraft, minecraft says I need abnormals_core 3.2.0 or above -- and abnormals_core doesn't exist on curseforge.

How do I get this to work ?

**Comment by ShockMicro** [comment]
This is multiple layers of updates in action here. Pollen is only needed for the 1.18 version, Abnormals Core is needed for 1.16. Abnormals Core was renamed to Blueprint, so that's the mod you're really looking for. Sorry for the trouble!
